In [1]:
# Importamos las librerías necesarias
import numpy as np

1. Cread un array de dos dimensiones de 5 filas y 3 columnas.

In [2]:
# Con el método random randint, creamos una matriz con valores entre 1 y 50, de 5x3
array1 = np.random.randint(1,50, (5,3))
array1

array([[27, 38, 48],
       [20,  4, 37],
       [ 4, 10, 29],
       [35, 43, 27],
       [ 5,  7, 26]])

Sobre el array creado anteriormente extraed:
- El valor de la primera fila y la segunda columna

In [3]:
# Usamos los índices para extraer los valores
array1[0,1]

38

- Los valores de la segunda fila y las dos primeras columnas

In [4]:
array1[1,:2]

array([20,  4])

- Extraed las filas pares (incluyendo la 0) y todas las columnas

In [5]:
# Al hablar de incluir la 0, entendemos que estamos hablando de posición de Python, y no humana
array1[::2,:]

array([[27, 38, 48],
       [ 4, 10, 29],
       [ 5,  7, 26]])

- Extraed los valores que sean mayores que 0.5.

In [6]:
# Extraemos un subset con la condición de que los valores sean mayores que 0.5 (En nuestro caso son todos)
array1[array1 > 0.5]

array([27, 38, 48, 20,  4, 37,  4, 10, 29, 35, 43, 27,  5,  7, 26])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
# Extraemos un subset con la condición de que los valores sean menores que 0.2 o mayores que 0.5 (En nuestro caso son todos de nuevo)
array1[(array1 < 0.2) | (array1 > 0.5)]

array([27, 38, 48, 20,  4, 37,  4, 10, 29, 35, 43, 27,  5,  7, 26])

2. Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.
- El segundo de 3 matrices, 2 filas y 5 columnas

In [10]:
array2 = np.random.rand(2,5,3)
print(array2)
print("-----------------------------------")
array3 = np.random.rand(3,2,5)
print(array3)

[[[0.13248907 0.33315516 0.74677517]
  [0.53985157 0.03631202 0.95373645]
  [0.26321776 0.47333583 0.20895358]
  [0.1472225  0.16642836 0.04799413]
  [0.13780651 0.13925267 0.34139148]]

 [[0.42640012 0.61319556 0.55890129]
  [0.60057873 0.83398526 0.09429619]
  [0.8288538  0.58094669 0.08582427]
  [0.35103573 0.06557503 0.48477586]
  [0.35361773 0.0327722  0.78802267]]]
-----------------------------------
[[[0.52453938 0.46091548 0.32222084 0.74104383 0.02587763]
  [0.44773689 0.29054076 0.9119143  0.89259518 0.71591004]]

 [[0.20880139 0.3552689  0.79163683 0.03188218 0.19617215]
  [0.87954553 0.75761224 0.2141172  0.84678238 0.52888457]]

 [[0.09183372 0.62411941 0.97890894 0.63947814 0.69377   ]
  [0.78835662 0.7301118  0.3594018  0.57035103 0.35300065]]]


- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [13]:
# Recuperamos la función realizada en el pair anterior
def chequear_array(array):
    print(f"La dimension del array es: {array.ndim}")  #aqui nos printea la dimension del array
    print(f"El tipo del array es: {array.dtype}")   #aqui nos printea el tipo del array
    print(f"El tamaño del array es: {array.size}")  #aqui nos printea el tamaño del array
    print(f"La forma del array es: {array.shape}")  #aqui nos printea la forma del array

In [14]:
chequear_array(array2)

La dimension del array es: 3
El tipo del array es: float64
El tamaño del array es: 30
La forma del array es: (2, 5, 3)


In [15]:
chequear_array(array3)

La dimension del array es: 3
El tipo del array es: float64
El tamaño del array es: 30
La forma del array es: (3, 2, 5)


- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [16]:
array2 + array3
# Nos da error porque no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
- .reshape()
- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos

In [17]:
# Con el método reshape le decimos el número de matrices, filas y columnas
array4 = np.reshape(array2, (3,2,5))
array4

array([[[0.13248907, 0.33315516, 0.74677517, 0.53985157, 0.03631202],
        [0.95373645, 0.26321776, 0.47333583, 0.20895358, 0.1472225 ]],

       [[0.16642836, 0.04799413, 0.13780651, 0.13925267, 0.34139148],
        [0.42640012, 0.61319556, 0.55890129, 0.60057873, 0.83398526]],

       [[0.09429619, 0.8288538 , 0.58094669, 0.08582427, 0.35103573],
        [0.06557503, 0.48477586, 0.35361773, 0.0327722 , 0.78802267]]])

In [18]:
# Al cambiarle la forma al array, ya podremos sumarlos.
array3 + array4

array([[[0.65702845, 0.79407065, 1.06899602, 1.2808954 , 0.06218965],
        [1.40147335, 0.55375852, 1.38525013, 1.10154876, 0.86313254]],

       [[0.37522975, 0.40326303, 0.92944335, 0.17113485, 0.53756362],
        [1.30594565, 1.3708078 , 0.7730185 , 1.44736111, 1.36286984]],

       [[0.18612991, 1.45297321, 1.55985563, 0.72530241, 1.04480573],
        [0.85393165, 1.21488766, 0.71301953, 0.60312323, 1.14102331]]])

In [19]:
# Con el método transpose, cambiamos la posición de los 3 ejes, diciendole en que lugar queremos que esté ahora
array5 = np.transpose(array2, (2,0,1))
array5

array([[[0.13248907, 0.53985157, 0.26321776, 0.1472225 , 0.13780651],
        [0.42640012, 0.60057873, 0.8288538 , 0.35103573, 0.35361773]],

       [[0.33315516, 0.03631202, 0.47333583, 0.16642836, 0.13925267],
        [0.61319556, 0.83398526, 0.58094669, 0.06557503, 0.0327722 ]],

       [[0.74677517, 0.95373645, 0.20895358, 0.04799413, 0.34139148],
        [0.55890129, 0.09429619, 0.08582427, 0.48477586, 0.78802267]]])

In [20]:
array5 + array3

array([[[0.65702845, 1.00076706, 0.5854386 , 0.88826633, 0.16368414],
        [0.87413702, 0.89111949, 1.74076811, 1.24363091, 1.06952777]],

       [[0.54195656, 0.39158091, 1.26497266, 0.19831054, 0.33542482],
        [1.49274109, 1.5915975 , 0.79506389, 0.91235741, 0.56165678]],

       [[0.83860889, 1.57785586, 1.18786252, 0.68747228, 1.03516147],
        [1.34725791, 0.82440799, 0.44522607, 1.05512689, 1.14102331]]])