## Ejercicios pair programming 13 diciembre: Numpy IV

In [1]:
import numpy as np

¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [4]:
np.random.seed(1)    #usamos seed para poder hacer dos array pseudo-aleatorios iguales
arr1 = np.random.random_sample((2,3))
print(arr1)


[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


In [5]:
np.random.seed(1)
arr2= np.random.random_sample((2,3))
arr2


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

Cread los siguientes arrays:

Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos 

almacenándolos en una variable.

Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus
 
valores únicos y guarda los datos en una variable.

In [10]:
arr3 = np.round(np.random.uniform(0,10, size = (2,3,5)) ,decimals = 0)
arr3

array([[[4., 5., 7., 2., 3.],
        [7., 8., 9., 8., 0.],
        [1., 8., 2., 3., 9.]],

       [[9., 6., 2., 8., 5.],
        [6., 8., 5., 5., 7.],
        [7., 3., 1., 8., 5.]]])

In [11]:
unicos3 = np.unique(arr3)      #extraemos los valores unicos del array
unicos3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
arr4 = np.random.binomial(10, 0.3, size = (2,3,5))
arr4

array([[[2, 3, 2, 2, 3],
        [3, 2, 3, 2, 3],
        [2, 3, 4, 2, 4]],

       [[3, 4, 4, 4, 3],
        [4, 3, 3, 3, 3],
        [1, 4, 3, 4, 3]]])

In [13]:
unicos4 = np.unique(arr4)    #extraemos los valores unicos del array
unicos4

array([1, 2, 3, 4])

En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad

las siguientes operaciones:

Elementos comunes entre los dos arrays

Unión de los dos arrays

¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [14]:
np.intersect1d(unicos3, unicos4)
#hemos sacado los elementos que estan en los dos array

array([1., 2., 3., 4.])

In [15]:
np.union1d(unicos3,unicos4)
#los elementos que estan en los dos array sin duplicados y ordenados

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:

np.setdiff1d(arr3, arr4)
#los elementos que estan en array3 pero no estan en array4s

array([0., 5., 6., 7., 8., 9.])

Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [18]:
array1 = np.random.randint(1,100, (80))
array2= np.random.randint(1,100, (80))
print(array1)
print(array2)

[82 74 28 40 88 10 15 32 57 57 59 80 28 51 75 70  3 58 24 96 26 42 10 67
 16 66 31 89 50 41 12 70  1 59 87 38 69 19 10 58 15 36 76 24 30 61 98  3
 20 87 46 86 85 85 61 46 25 76 56 66 83 52 13 37 42 75 97 96 86 32 68 77
 43  3 40 97 87 80  8 12]
[86 28 72 24 38 55 34  7 13 37 93  7 65  8 47  3 27 71 51 76 20 41 76 71
 98 74 23 81 81 45 42 67 36 88 50 75 28 95 51  2 22  6  7 42 69 83 11 65
  5 76 16 55 12  5 23  7 60 45 74 12 19 53 65 56 65 37 49 96 59 40 38 55
 93  6 27 16 92 56 11 70]


In [20]:
#sobreescribimos los array1 y array2 con los valores unicos de cada array original
array1 = np.unique(array1)     
array2 = np.unique(array2)


In [21]:
array1

array([ 1,  3,  8, 10, 12, 13, 15, 16, 19, 20, 24, 25, 26, 28, 30, 31, 32,
       36, 37, 38, 40, 41, 42, 43, 46, 50, 51, 52, 56, 57, 58, 59, 61, 66,
       67, 68, 69, 70, 74, 75, 76, 77, 80, 82, 83, 85, 86, 87, 88, 89, 96,
       97, 98])

In [22]:
array2

array([ 2,  3,  5,  6,  7,  8, 11, 12, 13, 16, 19, 20, 22, 23, 24, 27, 28,
       34, 36, 37, 38, 40, 41, 42, 45, 47, 49, 50, 51, 53, 55, 56, 59, 60,
       65, 67, 69, 70, 71, 72, 74, 75, 76, 81, 83, 86, 88, 92, 93, 95, 96,
       98])

In [23]:
#identificar los elementos que estan en array1 pero no en array2 y llamadle array3
array3 = np.setdiff1d(array1, array2)
array3


array([ 1, 10, 15, 25, 26, 30, 31, 32, 43, 46, 52, 57, 58, 61, 66, 68, 77,
       80, 82, 85, 87, 89, 97])

In [24]:
#identificar los elementos qeu estan en array 2 pero no en array1 y llamadle array4
array4 = np.setdiff1d(array2, array1)
array4

array([ 2,  5,  6,  7, 11, 22, 23, 27, 34, 45, 47, 49, 53, 55, 60, 65, 71,
       72, 81, 92, 93, 95])

In [25]:
#identificar los elementos presentes en ambos array y llamadle array5
array5 = np.intersect1d(array1, array2)
array5

array([ 3,  8, 12, 13, 16, 19, 20, 24, 28, 36, 37, 38, 40, 41, 42, 50, 51,
       56, 59, 67, 69, 70, 74, 75, 76, 83, 86, 88, 96, 98])

Sacamos el tamaño con size de cada array para conocer su longitud

In [27]:
array1.size

53

In [28]:
array2.size

52

In [29]:
array3.size

23

In [30]:
array4.size

22

In [31]:
array5.size

30

In [33]:
#el tamaño de array1 sera la suma de sus valores que estan en array1 pero no en array2 mas los valores que tienen en comun
array1.size == array3.size + array5.size

True

In [34]:
#el tamaño de array2 sera la suma de sus valores que estan en array2 pero no en array1 mas los valores que tienen en comun

array2.size == array4.size + array5.size

True