In [1]:
# Importamos las librerías necesarias
import numpy as np

1. Cread un array de 3 dimensiones de 2 matrices, 3 filas y 5 columnas, cuyos valores solo tengan 1 decimal.

In [2]:
# Utilizamos el metodo de numpy round para decirle el número de decimales que queremos
arr1 = np.round(np.random.rand(2,3,5), decimals= 1)
arr1

array([[[0.1, 0.4, 0. , 0.5, 0.1],
        [0.5, 0.9, 0.9, 1. , 0.5],
        [0.4, 0.2, 0.5, 0.6, 1. ]],

       [[0.1, 0.3, 0.3, 0.5, 0.8],
        [0. , 0.1, 0.2, 0.1, 0.8],
        [0. , 0.6, 0.1, 0.4, 0.7]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [3]:
# Con np.mean calculamos la media y con np.round redondeamos a un decimal
media_arr1 = np.round(np.mean(arr1), decimals= 1)
media_arr1

0.4

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
# Con np.max calculamos el valor máximo y con np.round redondeamos a un decimal
max_arr1 = np.round(np.max(arr1), decimals= 1)
max_arr1

1.0

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
# Con np.min calculamos el valor mínimo y con np.round redondeamos a un decimal
min_arr1 = np.round(np.min(arr1), decimals= 1)
min_arr1

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

    Reemplazamos los valores de la matriz vacía que acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
    - Si el valor del array es igual que la media, se reemplaza por "A".
    - Si el valor del array es mayor que la media, se reemplaza por "B".
    - Si el valor del array es menor que la media, se reemplaza por "C".
    - Si el valor es igual que el máximo, se reemplaza por "D".
    - Si el valor es igual que el mínimo, se reemplaza por "E".

In [6]:
"""
Creamos un array vacio con la forma y dimensiones del array anterior, 
pero especificamos que los datos serán tipo string, ya que vamos a insertarle
valores de ese tipo
"""
arr_vacio = np.empty_like(arr1, dtype= str)
arr_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [ ]:
d, e, f = np.where(arr1== 0.9)

In [8]:
a, b, c =np.where(arr1== 0.9)

numpy.ndarray

In [7]:
# iteramos por cada matriz del array original
for i in arr1:
    # iteramos por cada fila de la matriz
    for m in i:
        # iteramos por cada elemento de la fila
        for x in m:
            # si el elemento es igual a la media
            if x == media_arr1:
                # Buscamos la posición de ese elemento con np.where, y guardamos cada array de posiciones(matriz, fila y columna) en una variable separado
                d, e, f = np.where(arr1== x)
                # Convertimos las variables en una tupla con el índice de matriz, fila y columna de cada posición usando el método zip
                prueba = tuple(zip(d,e,f))
                # Mediante un contador y un while, usamos la tupla para modificar el valor, asegurandonos de pasar por todos los índices obtenidos
                p = 0
                while p < len(prueba):
                    arr_vacio[prueba[p]] = "A"
                    p += 1
            if x > media_arr1:
                p = 0
                d, e, f = np.where(arr1== x)
                prueba = tuple(zip(d,e,f))
                while p < len(prueba):
                    arr_vacio[prueba[p]] = "B"
                    p += 1
            if x < media_arr1:
                p = 0
                d, e, f = np.where(arr1== x)
                prueba = tuple(zip(d,e,f))
                while p < len(prueba):
                    arr_vacio[prueba[p]] = "C"
                    p += 1
            if x == max_arr1:
                p = 0
                d, e, f = np.where(arr1== x)
                prueba = tuple(zip(d,e,f))
                while p < len(prueba):
                    arr_vacio[prueba[p]] = "D"
                    p += 1
            if x == min_arr1:
                p = 0
                d, e, f = np.where(arr1== x)
                prueba = tuple(zip(d,e,f))
                while p < len(prueba):
                    arr_vacio[prueba[p]] = "E"
                    p += 1
arr_vacio

array([[['B', 'B', 'C', 'C', 'B'],
        ['B', 'E', 'C', 'D', 'B'],
        ['A', 'C', 'C', 'B', 'C']],

       [['C', 'A', 'A', 'D', 'B'],
        ['C', 'B', 'E', 'E', 'A'],
        ['B', 'C', 'D', 'B', 'C']]], dtype='<U1')

6. Realizamos un ejercicio similar al anterior, pero en este caso creamos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de 3 dimensiones con la misma forma que el primero que nos creamos.
    En este caso:
    - Si el valor del array creado en el ejercicio anterior es "A" o "B", lo reemplazaremos por 1.
    - Si el valor del array creado en el ejercicio anterior es "C" o "D", lo reemplazaremos por 2.
    - Si el valor del array creado en el ejercicio anterior es "E", lo reemplazaremos por 3.

    Una vez que todos los valores hayan sido reemplazados, cambiad la forma del array para que sea de 3 dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [8]:
# Creamos un array vacio unidimensional de 30 elementos
arr30 = np.empty(30)
arr30

array([0.9, 0.9, 0.4, 0.3, 0.8, 0.9, 0.1, 0.2, 1. , 0.7, 0.6, 0.5, 0.5,
       0.9, 0.3, 0.4, 0.6, 0.6, 1. , 0.8, 0.3, 0.7, 0.1, 0.1, 0.6, 0.7,
       0.2, 1. , 0.9, 0.2])

In [9]:
# Creamos un array convirtiendo el vacio en un array unidimensional, de manera que los dos arrays tengan la misma forma
arr_vacio_unidem = np.reshape(arr_vacio, 30)
arr_vacio_unidem

array(['B', 'B', 'C', 'C', 'B', 'B', 'E', 'C', 'D', 'B', 'A', 'C', 'C',
       'B', 'C', 'C', 'A', 'A', 'D', 'B', 'C', 'B', 'E', 'E', 'A', 'B',
       'C', 'D', 'B', 'C'], dtype='<U1')

In [10]:
# Iteramos por el array vacio unidimensional
for i in arr_vacio_unidem:
    # Si el elemento es igual a "A" o "B"
    if i == "A" or i == "B": 
        # Buscamos la posición del elemento en el array, lo metemos en una variable 
        d = np.where(arr_vacio_unidem== i)
        # iteramos por la variable para obtener la posición y modificamos el arr30 en esa posición
        for num in d:
            for yo in num:
                arr30[yo] = 1
        
    if i == "C" or i == "D":
        d = np.where(arr_vacio_unidem== i)
        for num in d:
            for yo in num:
                arr30[yo] = 2
    if i == "E":
        d = np.where(arr_vacio_unidem== i)
        for num in d:
            for yo in num:
                arr30[yo] = 3
print(arr30)
print("--------------------------")                  
arr_def = np.reshape(arr30, (2,3,5))
arr_def

[1. 1. 2. 2. 1. 1. 3. 2. 2. 1. 1. 2. 2. 1. 2. 2. 1. 1. 2. 1. 2. 1. 3. 3.
 1. 1. 2. 2. 1. 2.]
--------------------------


array([[[1., 1., 2., 2., 1.],
        [1., 3., 2., 2., 1.],
        [1., 2., 2., 1., 2.]],

       [[2., 1., 1., 2., 1.],
        [2., 1., 3., 3., 1.],
        [1., 2., 2., 1., 2.]]])